# Generated by Django 4.1.1 on 2022-09-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employee_date_of_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='filecsv',
            field=models.FileField(default='test.csv', upload_to='files'),
        ),
    ]
